services:
  backend:
    image: promptbeatai-backend
    hostname: promptbeatai-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SAMPLE_FOLDER=./assets/samples
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

  frontend:
    image: promptbeatai-frontend
    hostname: promptbeatai-frontend
    build:
      context: ./frontend/project
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
